apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: favourable-raccoon-java-quarkus
  janus-idp.io/tekton: favourable-raccoon-java-quarkus
  backstage.io/kubernetes-id: favourable-raccoon-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-demo 
  app.kubernetes.io/part-of: favourable-raccoon-java-quarkus
resources: 
- deployment.yaml
- route.yaml
- service.yaml
